version: 2.1

jobs:
  docker-build:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run: 
          name: Docker build command
          command: echo "Here we will build the docker"
  docker-run:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          name: Docker test command 
          command: echo "Here the docker image needs to be run"
  deploy:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          name: Deploy command
          command: echo "deploy command is executed"

workflows:
  version: 2

  docker-workflow:
    jobs:
      - docker-build
      - docker-run:
          requires:
            - docker-build
  
  deploy-workflow:
    jobs:
      - docker-build
      - docker-run:
          requires:
            - docker-build
      - deploy:
          requires:
            - docker-run

  


