version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: gau1rav/test-image
    docker:
      - image: cimg/node:15.10.0

jobs:
  build-docker:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Docker build command
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-docker: &publish-docker
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish image to DockerHub
          command: |
            echo "gaurav_Docker1" | docker login -u "gau1rav" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:<< parameters.IMAGE_TAG >>
            docker push $IMAGE_NAME:$IMAGE_TAG
  deploy-on-any:
    parameters:
      IMAGE_TAG:
        type: string
        default: "0.0:${CIRCLE_BUILD_NUM}"
    <<: *publish-docker
  deploy-on-master:
    parameters:
      IMAGE_TAG:
        type: string
        default: "LTS"
    <<: *publish-docker
  deploy-on-develop:
    parameters:
      IMAGE_TAG:
        type: string
        default: "LATEST"
    <<: *publish-docker
    
  # deploy-on-any:
  #     executor: docker-publisher
  #     steps:
  #       - attach_workspace:
  #           at: /tmp/workspace
  #       - setup_remote_docker
  #       - run:
  #           name: Load archived docker image
  #           command: docker load -i /tmp/workspace/image.tar
  #       - run:
  #           name: Publish image to DockerHub
  #           command: |
  #             echo "gaurav_Docker1" | docker login -u "gau1rav" --password-stdin
  #             IMAGE_TAG = "0.0:${CIRCLE_BUILD_NUM}"
  #             docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
  #             docker push $IMAGE_NAME:$IMAGE_TAG
  # deploy-on-develop:
  #     executor: docker-publisher
  #     steps:
  #       - attach_workspace:
  #           at: /tmp/workspace
  #       - setup_remote_docker
  #       - run:
  #           name: Load archived docker image
  #           command: docker load -i /tmp/workspace/image.tar
  #       - run:
  #           name: Publish image to DockerHub
  #           command: |
  #             echo "gaurav_Docker1" | docker login -u "gau1rav" --password-stdin
  #             docker push $IMAGE_NAME:latest
  # deploy-on-master:
  #     executor: docker-publisher
  #     steps:
  #       - attach_workspace:
  #           at: /tmp/workspace
  #       - setup_remote_docker
  #       - run:
  #           name: Load archived docker image
  #           command: docker load -i /tmp/workspace/image.tar
  #       - run:
  #           name: Publish image to DockerHub
  #           command: |
  #             echo "gaurav_Docker1" | docker login -u "gau1rav" --password-stdin
  #             docker tag $IMAGE_NAME:latest $IMAGE_NAME:LTS
  #             docker push $IMAGE_NAME:LTS

workflows:
  version: 2
  
  deploy-workflow:
    jobs:
      - build-docker
      - deploy-on-any:
          requires:
            - build-docker
          filters:
            branches:
              ignore:
                - master
                - develop
      - hold-for-approval:
          type: approval
          requires: 
            - build-docker
          filters:
            branches:
              only:
                - develop
                - master
      - deploy-on-master:
          requires:
            - hold-for-approval
          filters:
            branches:
              only:
                - master
      - deploy-on-develop:
          requires:
            - hold-for-approval
          filters:
            branches:
              only:
                -develop
