version: 2.1

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run: 
          name: Build command
          command: echo "build command is executed"
  test:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          name: Test command
          command: echo "test is executed"
  deploy:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - run:
          name: Deploy command
          command: echo "deploy command is executed"
