version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: gau1rav/test-image
    docker:
      - image: cimg/node:15.10.0

jobs:
  build-docker:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Docker build command
          command: docker build -t $IMAGE_NAME:latest
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  deploy-on-any:
      executor: docker-publisher
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - setup_remote_docker
        - run:
            name: Load archived docker image
            command: docker load -i /tmp/workspace/image.tar
        - run:
            name: Publish image to DockerHub
            command: |
              echo "gaurav_Docker1" docker login -u "gau1rav" --password-stdin
              IMAGE_TAG = "0.0:${CIRCLE_BUILD_NUM}"
              docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
              docker push $IMAGE_NAME:$IMAGE_TAG
  deploy-on-develop:
      executor: docker-publisher
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - setup_remote_docker
        - run:
            name: Load archived docker image
            command: docker load -i /tmp/workspace/image.tar
        - run:
            name: Publish image to DockerHub
            command: |
              echo "gaurav_Docker1" docker login -u "gau1rav" --password-stdin
              docker push $IMAGE_NAME:$latest
  deploy-on-master:
      executor: docker-publisher
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - run:
            name: List directories
            command: ls

        # - setup_remote_docker
        # - run:
        #     name: Load archived docker image
        #     command: docker load -i /tmp/workspace/image.tar
        # - run:
        #     name: Publish image to DockerHub
        #     command: |
        #       echo "gaurav_Docker1" docker login -u "gau1rav" --password-stdin
        #       IMAGE_TAG = "LTS"
        #       docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
        #       docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  
  deploy-workflow:
    jobs:
      - build-docker
      - deploy-on-any:
          filters:
            branches:
              ignore:
                - master
                - develop
      - deploy-on-master:
          filters:
            branches:
              only:
                - master
      - deploy-on-develop:
          filters:
            branches:
              only:
                -develop
